### ISSUE TITLE
cannot run scripts from command line

### ISSUE THREAD

**Issue by murphyk** [probml/JSL#24]
On my macbook pro, with jax[cpu] installed, I get this error
```
(base) kpmurphy-macbookpro1% python jsl/demos/kf_tracking.py     
Traceback (most recent call last):
  File "jsl/demos/kf_tracking.py", line 6, in <module>
    from jsl.demos.plot_utils import plot_ellipse
  File "/opt/anaconda3/lib/python3.8/site-packages/jsl/__init__.py", line 1, in <module>
    from . import lds, nlds, demos
  File "/opt/anaconda3/lib/python3.8/site-packages/jsl/lds/__init__.py", line 1, in <module>
    from . import kalman_filter, cont_kalman_filter
  File "/opt/anaconda3/lib/python3.8/site-packages/jsl/lds/cont_kalman_filter.py", line 9, in <module>
    from jax.ops import index_update
ImportError: cannot import name 'index_update' from 'jax.ops' (/opt/anaconda3/lib/python3.8/site-packages/jax/ops/__init__.py)
```
However, when I run the script inside of python, it works
```
 python
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jsl.demos import kf_tracking
>>> figdict = kf_tracking.main()
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
L2-filter: 3.2481
L2-smooth: 2.0450
```

**Comment by murphyk** [comment]
I made all the __init.py__ files be empty, so that the continous kf (which seems to be the root of the problem) is no longer being imported. Now it seems to work.
